### ISSUE TITLE
Bun binding problems: `dyld[XXX]: missing symbol called` and `error: could not locate the bindings file` causing unkillable process!

### ISSUE THREAD

**Issue by buzzy** [SanderGi/sqlite-auto-migrator#1] opened 2024-09-22 12:31 UTC
Running the migrator.make() completely freezez the process and I am not even able to kill it using "kill -9"!

```
Diffing schema:
  • Capturing pragmas...dyld[80832]: missing symbol called
```

I am running this on an empty database + a very simple schema:

```
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: sessions
CREATE TABLE "sessions" (
  id blob PRIMARY KEY NOT NULL,
  user blob NOT NULL,
  lastChecked timestamp NOT NULL
) WITHOUT ROWID;

-- Index: user
CREATE INDEX user ON sessions (user);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;

```
I am running this using Bun on a M2 Mac. Seems it's not compatible at all. Most likely this library (or a dependency) does not support non-x86 cpus yet. You might want to look into that.

**Comment by SanderGi** [comment] 2024-09-22 15:26
Thanks for making me aware of this issue! I have been running things on an M-series Mac as well but using Node.js (compiled for arm64). Does it work for you with Node.js? I will look into the Bun compatibility to see if that might be the cause

**Comment by SanderGi** [comment] 2024-09-22 15:29
Another note is, you don’t need the transaction in your schema. The migrator takes care of applying your schema within a transaction and temporarily disabling the foreign keys if they are enabled in your schema so you can remove those parts and just leave the one “PRAGMA foreign_keys = on;” at the top

**Comment by buzzy** [comment] 2024-09-22 16:16
Thanks! I just exported the schema using SQLiteStudio without editing it as a test. Node might work. Haven't tested it as I don't want to mix runtimes in my environment. I also write in typescript, so running it in node would mean adding extra layers like transpilers etc, which I don't need with Bun. My CI-environment runs "normal" x86, so I am testing if it works fine there, but it would be nice to be able to test things locally on the Mac :)

**Comment by buzzy** [comment] 2024-09-22 17:31
Nope, actually does not work on Bun on x86 either. My CI creates a production ready Bun-binary with all code and Bun-runtime in one file. Running that file gives error that package.json is missing. I do not get that problem if I don't import the "sqlite-auto-migrator" library, so something is definitely not playing nice with Bun.

Basically I am including the current .sql file inside my project (Bun binary file) and on first run, I have a "--update-database" flag, that compares the embedded .sql-file with the current database and performs the changes needed. That run fails with Bun.

**Comment by SanderGi** [comment] 2024-09-22 17:37
Thanks for taking the time to investigate with x86 Bun. I just confirmed your schema works on M1 Mac with Node.js but the migrator breaks with Bun. I have pin-pointed the issue to be with running [node-sqlite3](https://www.npmjs.com/package/sqlite3) with Bun. Specifically, the Database.each() method does not bind correctly with Bun. The error can be recreated with:

```ts
import sqlite3 from 'sqlite3';

const db = new sqlite3.Database('data.db');
db.each('SELECT * FROM sessions', (err, row) => {
    console.log(row);
});
```

Which yields `dyld[65381]: missing symbol called`.

I have filed an issue with node-sqlite3. In the mean time, I have pushed a temporary patch to sqlite-auto-migrator. Let me know if upgrading sqlite-auto-migrator to version 1.1.4 does not fix things for you. It seems to work with my Bun version (1.1.29)

**Comment by buzzy** [comment] 2024-09-22 17:38
Wow, that was quick work! I will test it now. Btw, Bun uses a own built-in sqlite library that is much faster than node-sqlite3, so I am not sure if the node-sqlite3 team will care :)

**Comment by buzzy** [comment] 2024-09-22 17:44
Not sure if I am doing something wrong, but this is what I get:

![image](https://github.com/user-attachments/assets/5b9f5bc5-5a3b-420d-bcb6-6ce83003641a)

**Comment by SanderGi** [comment] 2024-09-22 17:46
Weird. What is your version of Bun? If it is an older version, you might need to add sqlite3 as a [trusted dependency](https://bun.sh/docs/cli/install#trusted-dependencies) (https://github.com/oven-sh/bun/issues/5187)

**Comment by buzzy** [comment] 2024-09-22 17:48
I tried it with 1.1.20 and latest 1.1.29. Same issue.
I even tried clearing the Bun cache.
Looks like it searches for the bindings in the wrong path:

![image](https://github.com/user-attachments/assets/02fbc7d4-78df-443f-b20c-97c02964f121)

I also tried removing my node_modules and bun.lockb and re-downloaded all libs.

**Comment by SanderGi** [comment] 2024-09-22 18:11
Hmm, not sure why it searches in the wrong path for you but not for me. Did you install bun with `curl -fsSL https://bun.sh/install | bash`? Does the process.arch say 'arm64' and what is your macOS version? I'll try to see if I can reproduce your issue by clearing my cache

**Comment by buzzy** [comment] 2024-09-22 18:33
Yes, I installed the official way with curl. Yes, it's a arm64 binary. The x86 Bun binary does not even start. Not even if I would run it with Rosetta.

![image](https://github.com/user-attachments/assets/edfae336-9b7c-48aa-b0e9-82d8f8ed718b)

**Comment by buzzy** [comment] 2024-09-22 18:34
My test-script is very basic:

![image](https://github.com/user-attachments/assets/b8c7cf94-3a18-4475-8fe7-2a5efdc680da)

**Comment by buzzy** [comment] 2024-09-22 19:10
Ah, for some reason, Bun is trying to get sqlite3 from it's cache instead of node_modules and in the cache, there is no sqlite3 binary:

![image](https://github.com/user-attachments/assets/a90327de-f1ed-4b14-9d43-48b1a3f5355a)

**Comment by buzzy** [comment] 2024-09-22 19:25
If I copy the sqlite3 binary from node_modules to cache, I get error, so I guess something is wrong with Bun.

![image](https://github.com/user-attachments/assets/0139d264-ac6c-4790-b59e-c084699d37cc)

**Comment by SanderGi** [comment] 2024-09-22 19:39
It might be worth submitting a report to the Bun team. How did you copy things over to the cache? This is how my working cache looks:
[cache.zip](https://github.com/user-attachments/files/17090976/cache.zip)

What does your bunfig.toml look like? Perhaps [disabling the cache](https://bun.sh/docs/install/cache) will fix things:
```yaml
[install.cache]
# the directory to use for the cache
dir = "~/.bun/install/cache"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = true

# when true, always resolve the latest versions from the registry
disableManifest = true
```

**Comment by buzzy** [comment] 2024-09-22 23:05
Your cache looks exactly like mine. You can clearly see that there is no **node_sqlite3.node** binary in there. So if it works for you, it is definitely not using your cache, but the binary that exists in your **node_modules** dir. I do not use a bunfig.toml at all, so I use all defaults. I can try to disable the cache, but as the config says, it will still write to the .cache dir, so it sounds more like it just switches to another location.

For my test, I simply copied the entire contents from node_modules/sqlite3/* to the bun cache dir.

**Comment by SanderGi** [comment] 2024-09-23 04:54
I see. I think the better way to get the binary into the cache directory is to `cd ~/.bun/install/cache/sqlite3@5.1.7@@@1` and then run `bun install` (should be equivalent to copy pasting the installed node_modules/sqlite3 or setting the trustedDependencies but perhaps it makes a difference). I don't usually use Bun so I cannot explain why my installation finds the correct binary in the node_modules and yours does not, esp. since we both have no bunfigs. Perhaps you can try forcing it to use the node_modules one by providing a relative path? I'll keep trying to reproduce the issue on my M1 Mac

**Comment by SanderGi** [comment] 2024-09-23 05:06
If you delete node_modules and bun.lockb again, do you get any errors when running `bun install` and/or `bun run index.ts`?

I think I might have been able to reproduce a similar issue to yours when doing this:
![image](https://github.com/user-attachments/assets/a8046bb3-3993-4ace-a96b-72c7b6aaa4fc)
![image](https://github.com/user-attachments/assets/d745b4d7-aa5d-4032-bc6c-9e957c0f8cfe)
![image](https://github.com/user-attachments/assets/42e55b72-5a78-4a22-ac6a-cb2fdd96df93)

The fix was to run `bun pm cache rm && rm -rf node_modules && rm bun.lockb && bun install` again

**Comment by SanderGi** [comment] 2024-09-24 03:04
Update - @buzzy I reproduced your error message (from before messing with the missing binary in the cache) by running Bun from the parent directory:
![image](https://github.com/user-attachments/assets/1f286428-e0ff-4b44-8ba5-101aed1529b1)

And then reproduced the segmentation fault by running Bun globally with bunx:
![image](https://github.com/user-attachments/assets/bbc1768d-2331-4da9-acb2-f72152fddc66)

As well as by adding the binary to the cache with `cd ~/.bun/install/cache/sqlite3@5.1.7@@@1 && bun install` and running from the parent directory:
![image](https://github.com/user-attachments/assets/60e84826-b9f0-4255-b570-545a679668a9)

A similar (but more informative) error happens with Node.js (since it does not default to running the global cached package and instead complains there is no local package found when running this way):
![image](https://github.com/user-attachments/assets/28b1fc31-3448-45d4-bfbb-a69e42120976)

And no error occurs running using the global Node.js package (since it installs and binds the binary correctly): 
![image](https://github.com/user-attachments/assets/021ff650-c443-40ed-bde0-f13114fea5e1)

Now that I can somewhat reproduce the error, I have found a potential work-around. Ideally Bun would work with binaries in the cache, but since it doesn't, you can make it aware of the node_modules binary by setting its working directory relative to the file being executed to guarantee it points at the folder with the package.json and node_modules: 
```ts
import path from 'path';

process.chdir(path.join(__dirname, '..'));

import { Migrator } from 'sqlite-auto-migrator';

const migrator = new Migrator();

await migrator.make();
await migrator.migrate();
```

Something similar might work for you. Let me know if it does.

**Comment by buzzy** [comment] 2024-09-24 20:08
Thank you! That actually solved the problem! So I guess Bun has a bug. I haven't tested it on "bun build" yet though. Hopefully it will still work when Bun bundles everything to one binary.

One question; Do I really need that "migration" table in the database? Is there a way to turn that off? As my CI simply has a sql-file with the latest schema and the CI always compares the "production" database with the schema and changes it, what exactly would I need the migration table for? I take a backup of the database before, so I don't really need any revert functionality.

**Comment by buzzy** [comment] 2024-09-24 21:00
I have issues with it getting stuck and never finishes. It only happens randomly though.

![image](https://github.com/user-attachments/assets/9b9cee53-bb6f-45b3-bb65-b045ff386f66)

![image](https://github.com/user-attachments/assets/0533b41d-e075-4898-a31c-59de13ecb047)

When that happens, the tables are left in a locked state:

![image](https://github.com/user-attachments/assets/13c8e3d7-daaa-42e0-806c-15c176510f81)

Also, is there a way to prevent it from creating the "migrations" table in the database and "migrations" directory? I do not need those as I am not checking in any versions or rollback features in git. I simply want it to compare the .sql-file with the database-file and create a "migration-file" in RAM and then execute it without leaving any traces.

**Comment by SanderGi** [comment] 2024-09-24 22:02
Great! Happy to hear the workaround worked for you as well. Let me know whether it works with "bun build" when you test it

These are excellent inquiries. I have split them up into separate issues to make the conversation easier to follow. This issue will remain for the bun binary binding, #2 will be for the deadlock, #3 for the "migrations" table and directory issue

**Comment by buzzy** [comment] 2024-10-02 19:16
I'm afraid that I get another issue regarding the sqlite3 library when using "bun build". When running the resulting binary, I get this:

![image](https://github.com/user-attachments/assets/a24597f9-a9eb-4e3f-90d0-3a7db8ee227a)

You should be able to reproduce it by running this to generate a binary:

`bun build --compile --minify --sourcemap ./src/server.ts --outfile ./src/server.exe`

I have reported it to the Bun team as well: https://github.com/oven-sh/bun/issues/14301

**Comment by SanderGi** [comment] 2024-10-03 10:58
Thanks for trying this out and reporting with bun. After looking into it, I don't think Bun build with --compile supports the necessary options to bundle in the node-sqlite3 binaries. The workaround I've settled for is to use the built-in bun:sqlite when running via bun and use node-sqlite3 with node/deno. You should be able to try it out via the latest commit on the main branch `bun install github:SanderGi/sqlite-auto-migrator`. Let me know if this fixes the error for you and I can publish a package version to npm

**Comment by buzzy** [comment] 2024-10-05 19:16
Seems you are using some post-install-script that is not trusted by Bun by default. That script also seems to require "husky"?

![image](https://github.com/user-attachments/assets/70f98676-4e2f-4834-be4e-c6bd67e18883)

**Comment by buzzy** [comment] 2024-10-05 19:24
Seems like my source .sql file can't be found by sqlite-auto-migrator when it's embedded inside the Bun binary:

![image](https://github.com/user-attachments/assets/96c127f7-12a2-412d-a476-a2c30a49c575)

I am still importing it like this and it works fine if I run the .ts file manually without building:

![image](https://github.com/user-attachments/assets/12a5d026-f379-4597-aa26-3541b195d70f)

**Comment by buzzy** [comment] 2024-10-05 19:28
btw, the deadlock seems to be fixed by switching to Buns own sqlite lib! So all works fine now, except reading the .sql file from within the Bun binary after using "bun build". Thank you so much for your efforts! I did not even expect that you would make special cases for Bun, that's why I did not even ask for it before :)

**Comment by SanderGi** [comment] 2024-10-05 20:25
> Seems you are using some post-install-script that is not trusted by Bun by default. That script also seems to require "husky"?
> 
> ![image](https://private-user-images.githubusercontent.com/344597/373900092-70f98676-4e2f-4834-be4e-c6bd67e18883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTkyNTEsIm5iZiI6MTcyODE1ODk1MSwicGF0aCI6Ii8zNDQ1OTcvMzczOTAwMDkyLTcwZjk4Njc2LTRlMmYtNDgzNC1iZTRlLWM2YmQ2N2UxODg4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQyMDA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTk5MWEyNTdhYmIwMDY1YmI4NzExODNjN2Q4ZTkxMGU1ZWY5MmJiMTU1YzRmNWYwMDkzYzY3ZGE5NWRmMjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YnzJ4arujcWKSWsiN_8UjcJVGfNzgbseBaaScIWEt64)

Don't worry about the prepare script, it is only supposed to run for local development, [not when installing the package](https://github.com/oven-sh/bun/issues/5017) but installing from Github makes Bun think it should run it. I use Husky to automatically run tests, linting, and formatting before commits

**Comment by SanderGi** [comment] 2024-10-05 20:28
> Seems like my source .sql file can't be found by sqlite-auto-migrator when it's embedded inside the Bun binary:
> 
> ![image](https://private-user-images.githubusercontent.com/344597/373900505-96c127f7-12a2-412d-a476-a2c30a49c575.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTkyNTEsIm5iZiI6MTcyODE1ODk1MSwicGF0aCI6Ii8zNDQ1OTcvMzczOTAwNTA1LTk2YzEyN2Y3LTEyYTItNDEyZC1hNDc2LWEyYzMwYTQ5YzU3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQyMDA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDY3MDljMmVkMGI2MDVkZTFmNDQzZmFhM2UyNzg1OTg4MjZkN2IxYjllNzVjMTAwNTcxM2ZkM2FjYTEzZTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8KwSiwruW5wVhi8s8m0Rhp9KG7Mc_YgoBZFKmnfWKUA)
> 
> I am still importing it like this and it works fine if I run the .ts file manually without building:
> 
> ![image](https://private-user-images.githubusercontent.com/344597/373900580-12a5d026-f379-4597-aa26-3541b195d70f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTkyNTEsIm5iZiI6MTcyODE1ODk1MSwicGF0aCI6Ii8zNDQ1OTcvMzczOTAwNTgwLTEyYTVkMDI2LWYzNzktNDU5Ny1hYTI2LTM1NDFiMTk1ZDcwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQyMDA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGQ0MDY0MTQ4OTkzNmI4MDczZWE2NzQxYzUyMmNiNDBkZTRiMjBjY2QzYWIxZjgzMDQ5ZTNlYjg4NTkzNDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QyUhXIwGGCJHv7sXL0ZJTS6bsLSqVyZ3D2hcrviSJw0)

It seems Bun does not support the Node.js file functions with $bunfs:
```ts
import sessions from "./schema1.sql" with { type: "file"};

const file = Bun.file(sessions);
console.log(await file.exists()); // true, successfully finds the file

import { accessSync, constants } from "node:fs";

accessSync("./schema1.sql", constants.R_OK); // Works, finds the file

accessSync(sessions, constants.R_OK) // Errors, does not find the file
```
As a quick workaround, you can keep the schema file separate from the compiled binary and pass in its local path directly to the migrator. I'll also go through and make exceptions for Bun in the code so it uses Bun.file when run via Bun

**Comment by SanderGi** [comment] 2024-10-05 20:35
> btw, the deadlock seems to be fixed by switching to Buns own sqlite lib! So all works fine now, except reading the .sql file from within the Bun binary after using "bun build". Thank you so much for your efforts! I did not even expect that you would make special cases for Bun, that's why I did not even ask for it before :)

Happy to hear that the deadlock is fixed for you. Thank you for your help debugging these issues! Would you be okay having your Github username credited in the readme for your help with Bun compatibility, deadlocks, and testing the declarative migrations?

Ideally we would not need special cases for Bun, but it seems it is the only way to make it work (perhaps in the future, Bun will be more compatible with Node.js)

**Comment by buzzy** [comment] 2024-10-05 21:11
Sure, it would be an honor!

I would prefer to not need to deploy any additional files, except the binary, so I will simply wait for your change to Bun builtin fs lib. Really awesome work so far!

**Comment by SanderGi** [comment] 2024-10-05 21:41
Makes sense. You should be able to use bun embedded files for the schemas using the latest commit now. Lmk if it works for you

**Comment by buzzy** [comment] 2024-10-06 00:58
I just performed my first 100% successful database upgrade through my CI system! Awesome product :)

![image](https://github.com/user-attachments/assets/20a03d09-a17e-42a7-9478-da12e805934e)

**Comment by SanderGi** [comment] 2024-10-09 06:12
Congrats! I'm glad we could get it to work in the end. I have published the Bun compatibility fixes to npm (version 1.2.0) and will close this issue. Don't hesitate to open another issue if you run into problems. Thanks for all your help and good luck with your projects

**Closed as completed by SanderGi** 2024-10-09 06:12 UTC
Labels: bug, Runtime:Bun

**Comment by lutfi-haslab** [comment] 2025-02-05 03:15
> I'm afraid that I get another issue regarding the sqlite3 library when using "bun build". When running the resulting binary, I get this:
> 
> ![image](https://github.com/user-attachments/assets/a24597f9-a9eb-4e3f-90d0-3a7db8ee227a)
> 
> You should be able to reproduce it by running this to generate a binary:
> 
> `bun build --compile --minify --sourcemap ./src/server.ts --outfile ./src/server.exe`
> 
> I have reported it to the Bun team as well: [oven-sh/bun#14301](https://github.com/oven-sh/bun/issues/14301)

sorry to ask this after issue close, i have same problem with building into binary, how you handle this bindings not found?
<img width="686" alt="Image" src="https://github.com/user-attachments/assets/11f2de89-9e09-4979-b92f-7dfa585910b4" />

**Comment by SanderGi** [comment] 2025-02-05 04:23
> sorry to ask this after issue close, i have same problem with building into binary, how you handle this bindings not found? <img alt="Image" width="686" src="https://private-user-images.githubusercontent.com/108409669/409813261-11f2de89-9e09-4979-b92f-7dfa585910b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3Mjg4MzUsIm5iZiI6MTczODcyODUzNSwicGF0aCI6Ii8xMDg0MDk2NjkvNDA5ODEzMjYxLTExZjJkZTg5LTllMDktNDk3OS1iOTJmLTdkZmE1ODU5MTBiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwNVQwNDA4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDE3OGM4ZGRkOWY0N2ZiZGZiNWExYTgzOGQzYTdjZWI2N2NkODZiYjJlMjcxMTMyNzA2YTQzNzg0MWYzZmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._gBpaKKoaU_c6vKERQEwt2Qc-N_z7sruausuwwBjFsY">

@lutfi-haslab, looks like your error is not related to sqlite-auto-migrator but to another library you are using, [hnswlib](https://www.npmjs.com/package/hnswlib-node). They might not support bun bindings. I suggest posting an issue in their repo. If you can reproduce the error using just sqlite-auto-migrator or have an example that shows this error only occurs when hnswlib is used in conjunction with sqlite-auto-migrator, feel free to open a new issue here with example code to reproduce the error. If hnswlib is not interested in supporting bun bindings, you might be able to use a workaround similar to [what we tried for sqlite-auto-migrator before deciding to use the builtin bun sqlite](https://github.com/SanderGi/sqlite-auto-migrator/issues/1#issuecomment-2370017429), but again, they would best be able to advice so definitely ask in their repo.
